### ISSUE TITLE
Erreur "adactive_sas_saml2_bridge.processor.hosted_idp"

### ISSUE THREAD

**Issue by tbreton14** [AdactiveSAS/saml2-bridge-bundle#1]
La déclaration d'un service semble manquée dans cette déclaration.

The service "adactive_sas_saml2_bridge.processor.hosted_idp" has a dependency on a non-existent service "adsum_user.saml.service_provider_repository".

**Comment by tbreton14** [comment]
Pour contourner le problème, le service créé et associé à la classe ServiceProviderRepository doit absolument s'appeler "adsum_user.saml.service_provider_repository".

**Comment by moroine** [comment]
Thank for reporting that issue,

I fixed it on v0.2.2 ! If you found any other issue, please report them !
