### ISSUE TITLE
Azure Active Directory

### ISSUE THREAD

**Issue by marvoh** [AdactiveSAS/saml2-bridge-bundle#16]
This is not an issue but a request for information.

I am currently using this your bundle as an IDP and it's working well. A new requirement has come up to implement my application as the SP to work with an Azure Active Directory IDP through SAML2.

How would I go about doing that?

**Comment by moroine** [comment]
Hi,

Unfortunatly this repository is intended to support identity provider for now. This choice has been made because I think there are a lot of good saml service provider library which is not really the case for IDP.

So I advice you to have a look at another library.
