### ISSUE TITLE
We seem to be back to this issue again

### ISSUE THREAD

**Issue by marvoh** [AdactiveSAS/saml2-bridge-bundle#17]
request.CRITICAL: Uncaught PHP Exception AdactiveSas\Saml2BridgeBundle\Exception\RuntimeException: "Could not process Request, error: "The SAMLRequest is expected to be signed but it was not""

**Comment by GDXbsv** [comment]
"wantSignedAuthnRequest" => false,

Try to set these option to false.

**Comment by marvoh** [comment]
It worked. Thanks
