### ISSUE TITLE
Unexpected behaviour

### ISSUE THREAD

**Issue by marvoh** [AdactiveSAS/saml2-bridge-bundle#18]
I am getting the following error when trying to log in. Do you think it would be related to something in this bundle?

Request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to DOMNode::appendChild() must be an instance of DOMNode, null given" at /vendor/simplesamlphp/saml2/src/SAML2/Assertion.php line 1537 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to DOMNode::appendChild() must be an instance of DOMNode, null given at /vendor/simplesamlphp/saml2/src/SAML2/Assertion.php:1537)"}

**Comment by GDXbsv** [comment]
Please add a call stack.

**Comment by marvoh** [comment]
Wow, how do I even reach that as it's called by the bundle. Let me investigate

**Comment by moroine** [comment]
You need to go into `/app_dev.php/_profiler` page  then look for the request failing. You will have all the information needed

**Comment by marvoh** [comment]
Sorry, my mind wasn't even there. Difficult week. Here we go:


    `Symfony\Component\Debug\Exception\ContextErrorException:
    Warning: DOMDocument::createTextNode() expects parameter 1 to be string, array given

      at vendor/simplesamlphp/saml2/src/SAML2/Assertion.php:1537
      at SAML2_Assertion->addAttributeStatement(object(DOMElement))
     (vendor/simplesamlphp/saml2/src/SAML2/Assertion.php:1335)
      at SAML2_Assertion->toXML(object(DOMElement))
     (vendor/simplesamlphp/saml2/src/SAML2/Response.php:75)
     at SAML2_Response->toUnsignedXML()
     (vendor/simplesamlphp/saml2/src/SAML2/Message.php:447)
     at SAML2_Message->toSignedXML()
     (vendor/adactive-sas/saml2-bridge-bundle/src/SAML2/Binding/HttpPostBinding.php:152)
      at AdactiveSas\Saml2BridgeBundle\SAML2\Binding\HttpPostBinding-
    >getResponseForm(object(SAML2_Response), true)
     (vendor/adactive-sas/saml2-bridge-bundle/src/SAML2/Binding/HttpPostBinding.php:127)
      at AdactiveSas\Saml2BridgeBundle\SAML2\Binding\HttpPostBinding-
    >getSignedResponseForm(object(SAML2_Response))
     (vendor/adactive-sas/saml2-bridge-bundle/src/SAML2/Binding/HttpPostBinding.php:62)
      at AdactiveSas\Saml2BridgeBundle\SAML2\Binding\HttpPostBinding-
    >getSignedResponse(object(SAML2_Response))
     (vendor/adactive-sas/saml2-bridge-bundle/src/SAML2/Provider/HostedIdentityProviderProcessor.php:387)
      at AdactiveSas\Saml2BridgeBundle\SAML2\Provider\HostedIdentityProviderProcessor-
       >continueSingleSignOn()
     (vendor/adactive-sas/saml2-bridge-bundle/src/SAML2/Provider/HostedIdentityProviderProcessor.php:189)
      at AdactiveSas\Saml2BridgeBundle\SAML2\Provider\HostedIdentityProviderProcessor->onKernelResponse(object(FilterResponseEvent), 'kernel.response', object(TraceableEventDispatcher))
     at call_user_func(array(object(HostedIdentityProviderProcessor), 'onKernelResponse'), object(FilterResponseEvent), 'kernel.response', object(TraceableEventDispatcher))
     (vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php:104)
      at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(object(FilterResponseEvent), 'kernel.response', object(ContainerAwareEventDispatcher))
      at call_user_func(object(WrappedListener), object(FilterResponseEvent), 'kernel.response', object(ContainerAwareEventDispatcher))
     (vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:212)
     at Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.response', object(FilterResponseEvent))
     (vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:44)
      at Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.response', object(FilterResponseEvent))
     (vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php:139)
     at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch('kernel.response', object(FilterResponseEvent))
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:193)
      at Symfony\Component\HttpKernel\HttpKernel->filterResponse(object(RedirectResponse), object(Request), 1)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:132)
      at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68)
      at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:169)
     at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (web/app.php:16)`

**Comment by GDXbsv** [comment]
Looks something wrong with an assertions config.  Please show your ServiceProviderConfiguration.
Also you could use debugger and figure out what do you have inside those array.

**Comment by marvoh** [comment]
$this->spMap["https://sp.com/saml/acs"] = new ServiceProvider(
            [
                /**
                * Returns the contents of an X509 pem certificate, without the '-----BEGIN CERTIFICATE-----'         
                * '-----END CERTIFICATE-----'.
                *
                * @return null|string
                */
                'certificateData' => 'data removed',

                /**
                * Returns the full path to the (local) file that contains the X509 pem certificate.
                *
                * @return null|string
                */
                "certificateFile" => "",

                /**
                * @return null|string
                */
                "entityId" => "https://sp.com/saml/acs",

                /**
                * @return null|bool
                */
                "assertionEncryptionEnabled" => true,
                "wantSignedAuthnRequest" => false,

                "assertionConsumerUrl" => "https://sp.com/saml/acs",
                "assertionConsumerBinding" => \SAML2_Const::BINDING_HTTP_POST,
                "singleLogoutUrl" => "https://sp/saml/logout ",
                "singleLogoutBinding" => \SAML2_Const::BINDING_HTTP_REDIRECT
            ]

**Comment by GDXbsv** [comment]
Hard to say something. You have to debug it.
Maybe @moroine  could say something.

**Comment by moroine** [comment]
Hi,
I follow the issue, but I've no access to a computer with the project to dig in. I'll check tomorrow, by the time give me clue please like the Response object at  AdactiveSas\Saml2BridgeBundle\SAML2\Binding\HttpPostBinding-
>getResponseForm using dump.

Otherwise you can create a test bundle using the development keys to reproduce a failing test (would be awesome, and ensure you the bug would be fixed forever), or if it's too complicated for you, just create a public repo as example and make it failing using

**Comment by moroine** [comment]
Hi, 

I also need you to add `dump` at `vendor/simplesamlphp/saml2/src/SAML2/Assertion.php:1537` to get value of `$value`, `$name` and `$values`

**Comment by marvoh** [comment]
Hi, sorry had travelled. I am now back. Let me revert per sec

**Comment by marvoh** [comment]
name: 
`"email"`

$value
```
array:1 [▼
  0 => "my@email.com"
]
```

$values:
```
array:1 [▼
  0 => array:1 [▼
    0 => "my@email.com"
  ]
]
```

Funny thing happened. The SP still redirects to authentication page regardless of whether I'm logged in or not

**Comment by moroine** [comment]
Ok so the issue is with the function `$document->createTextNode($value)` which expect a string and you give an array ! 

The error should come from `AssertionBuilder::setAttributes` or `AssertionBuilder::setAttribute`. 

Could you send us your code implying `AssertionBuilder::setAttributes`, `AssertionBuilder::setAttribute` and `ServiceProvider::attributes` property ?

**Comment by marvoh** [comment]
//Event Subscriber
    `class SamlSubscriber implements EventSubscriberInterface
    {
    protected $token_storage;

    public function __construct(TokenStorageInterface $token_storage)
    {
      $this->token_storage = $token_storage;
    }

    public static function getSubscribedEvents()
    {
        // return the subscribed events, their methods and priorities
        return array(
               'Saml2Events::SSO_AUTHN_GET_RESPONSE' => 'addEmail',
        );
    }

    public function addEmail(GetAuthnResponseEvent $event)
    {
      $assertionBuilders = $event->getAuthnResponseBuilder()->getAssertionBuilders();
      $assertionBuilders[0]->setAttribute('email',[$this->token_storage->getToken()->getUser()->getEmail()]);
      $event->getAuthnResponseBuilder()->setAssertionBuilders($assertionBuilders);
      return $event->getAuthnResponseBuilder()->getResponse();
    }
      }`


Is that all you require or should I post more?

**Comment by moroine** [comment]
Try this instead !

```php
public function addEmail(GetAuthnResponseEvent $event)
{
  $assertionBuilders = $event->getAuthnResponseBuilder()->getAssertionBuilders();
  $assertionBuilders[0]->setAttribute('email', $this->token_storage->getToken()->getUser()->getEmail());
  $event->getAuthnResponseBuilder()->setAssertionBuilders($assertionBuilders);
  return $event->getAuthnResponseBuilder()->getResponse();
}
```
