### ISSUE TITLE
Success Handler

### ISSUE THREAD

**Issue by soromamadou** [AdactiveSAS/saml2-bridge-bundle#19]
Hello, thanks for the bundle. Its work as a charm. 
But, i got an issue after login with the idp. Everything is ok, after redirected from the sp. But when i go directly to the idp and connecte the user, i am not connected in the sp.

For the logout, it's works very well after adding in security.yml
logout:
        handlers: [adactive_sas_saml2_bridge.logout.handler]

But you haven't talk about the handler for login.
Do you have any solution about this?
Thanks!

**Comment by soromamadou** [comment]
I got this in log file: app.DEBUG: Cannot perform authentication success [] []
I this it come from "AdactiveSas\Saml2BridgeBundle\SAML2\Provider\HostedIdentityProviderProcessor" on the method "onAuthenticationSuccess"

**Comment by moroine** [comment]
Hi, 

This is not an issue, this is the SAML process. When you login in IDP you cannot login in all registered SP because: 

- You don't really know on what SP the user want to be logged in
- The login would be terribly long (Imagine being redirected to all the SP)

But if you're already logged in into the IDP and go to the SP it will

- Redirect to IDP
- Redirect to SP (without showing a form, except if the SP require an explicit login)

But the logout act differently, the IDP retain a list of all SP you are logged in. Once you logout, the IDP will force logout on all SP for obvious security reasons.

If it's not clear enough, let me use an example: The Google Authentication ! This is a SAML based (I think though), and when you login into Google, you're not automatically logged in all the services you liked with.

**Comment by soromamadou** [comment]
OK. Forgive my ignorance. I am newbie with SAML. 
But what i notive with google is that, after login at https://accounts.google.com, i am redirected to https://myaccount.google.com/.

At the same time if i reload youtube page in another tab (where i wasn't log in), i see that i am automatically login with the same credentials as with https://myaccount.google.com/   .
I got the same with gmail and docs.google.com  . For gmail and docs.google.com i thinks it's normal because i am redirected to accounts.google when i am not connected. But youtube works without login!

Perhaps google make a king of request when user is not connected everytime after reloading the page. That's the workflow i am looking. 
Could you please help me know if there is a way to de that with this bundle ?

Thanks

**Comment by moroine** [comment]
Yeah, google is working like this but only for its own services. 

What I mean for SAML services it's more the "Login with Google", so when you login to Google you're not in all linked ones.

But I think there is a feature into SAML to ask for single sign on in implicit mode (which is not supported yet in that bundle).

The idea is:
   - Redirect to IDP
        - If the user is logged redirect back with success response
        - If not redirect back with failure response (instead of process login)

So it would permit to your SP to check for logged in client without asking for explicit login

Is that what you need ?

**Comment by soromamadou** [comment]
yes, that's what i need for now.
How can i get the implicit mode what you're talking about ?

**Comment by moroine** [comment]
Hi you can find the "bible" here: https://www.samltool.com/saml_documentation.php

So if you check out the (core document)[http://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf] at page 49 you got the **AuthnRequest** schema. 

And there is a very interesting property named **IsPassive** which is excatly what you need ! 

At my great supprise it seem to be supported ! You can have a look at (here[https://github.com/AdactiveSAS/saml2-bridge-bundle/blob/master/src/SAML2/Provider/HostedIdentityProviderProcessor.php#L561] which test the passive attribute. It generate `InvalidSamlRequestException` which is catched (here)[https://github.com/AdactiveSAS/saml2-bridge-bundle/blob/master/src/SAML2/Provider/HostedIdentityProviderProcessor.php#L330] and send the proper AuthnFailedResponse !

This hasn't been tested ! So don't hesitate to give us feedback !

**Comment by soromamadou** [comment]
Hello,
I test it. It works with this commande from the SP:
`
$auth = new OneLogin_Saml2_Auth();
$isPassive = true;
$auth->login(null, array(), false, $isPassive, false, true);
`
But the behavior is like gmail with accouts.google.com.
It don't know if there is a way to check only the state with like curl (like youtube do), not to be redirected.
Anyway, i think i can start with that.
If you have an idea to get youtube workflow i am taker. 
 Thanks for help! :+1:

**Comment by moroine** [comment]
Sure ! 

Will keep you updated
