### ISSUE TITLE
Support for Conditions -> AudienceRestriction on signed requests

### ISSUE THREAD

**Issue by guice** [AdactiveSAS/saml2-bridge-bundle#22]
When signing requests, SAML providers would verify it's a valid audience member. &lt;Conditions> element supports a sub-element called &lt;AudienceRestriction> that SPs use to assert itself is a valid recipient.

The lack of this element is resulting in issues with third party apps that expect it to be present (against SAML Specs, I know...) when testing certified responses.

**Comment by guice** [comment]
Here, this is what I'm looking for. This is within `/simplesamlphp/saml2/src/SAML2/Assertion.php` Ln:1396

```php
if ($this->validAudiences !== NULL) {
    $ar = $document->createElementNS(SAML2_Const::NS_SAML, 'saml:AudienceRestriction');
    $conditions->appendChild($ar);

    SAML2_Utils::addStrings($ar, SAML2_Const::NS_SAML, 'saml:Audience', FALSE, $this->validAudiences);
}
```

Need to set validAudiences in `SAML2/Builder/AssertionBuilder.php` to the SP Entity ID:

Within `HostedIdentityProviderProcessor::buildAuthnResponse()`
```php
$assertionBuilder->getAssertion()->setValidAudiences([$serviceProvider->getEntityId()]);
```

**Comment by moroine** [comment]
Hi, 

Yeah `$assertionBuilder->getAssertion()->setValidAudiences([$serviceProvider->getEntityId()]);` it's what you need.

So you just need to listen [that event](https://github.com/AdactiveSAS/saml2-bridge-bundle/blob/master/src/SAML2/Event/Saml2Events.php#L26) which will be fired with [GetAuthnResponseEvent](https://github.com/AdactiveSAS/saml2-bridge-bundle/blob/master/src/SAML2/Event/GetAuthnResponseEvent.php). Then you will have access to the builder

**Comment by guice** [comment]
> So you just need to listen that event which will be fired with GetAuthnResponseEvent. Then you will have access to the builder

Like that idea... I did an overload, however, this idea is better. I'll play with this.
