### ISSUE TITLE
private_key and public_key cannot be set as cert contents

### ISSUE THREAD

**Issue by guice** [AdactiveSAS/saml2-bridge-bundle#23]
We have environment files. We want to be able to set our certificates in line, but code is extremely adamant on using file_get_contents for these two key values.

Ideally:
```yml
# [...]
            private_key '%local_config.pem%'
            public_key '%local_config.cert%'
```

And those values will be the certificate contents, not file paths.

While I have found the option to set public certs within the Service Providers, nothing I did would allow me to set private cert contents.

**Comment by moroine** [comment]
Hi again,

Indeed it's not possible, but this shouldn't be too hard to make it working. Unfortunately I don't have time to work on it currently.

What about doing a PR ? 

Just to explain you how it's working:
- There is the configuration [here](https://github.com/AdactiveSAS/saml2-bridge-bundle/blob/master/src/DependencyInjection/Configuration.php#L80)
- Then it's parsed [here](https://github.com/AdactiveSAS/saml2-bridge-bundle/blob/master/src/Entity/HostedEntities.php#L92). You got all the configuration under `identityProviderConfiguration`
- After I create the configuration for the HostedIdentityProvider [here](https://github.com/AdactiveSAS/saml2-bridge-bundle/blob/master/src/Entity/HostedEntities.php#L121)
- As the inheritance hierachy is HostedIdentityProvider --> IdentityProvider --> SAML2_Configuration_IdentityProvider where you have the choice to use either certificate, or data directly [see here](https://github.com/simplesamlphp/saml2/blob/master/src/SAML2/Configuration/IdentityProvider.php#L18)


What about adding new configuration option `private_key_data` & `public_key_data` ?

**Comment by guice** [comment]
Unfortunately, sending a PR is out of my hands. I'm unable to.. Feel free to close this out if you don't wish to add this functionality or somebody else is capable. I've found a work-around on our end to do what we need.

**Comment by moroine** [comment]
Too bad, I'll close it so :disappointed_relieved:
